builds:
    - id: filefusion
      main: ./cmd/filefusion/main.go
      binary: filefusion
      goos:
          - linux
          - windows
      goarch:
          - amd64
          - arm64
      env:
          - CGO_ENABLED=1
      flags:
          - -tags=bash cpp csharp golang css html java php kotlin javascript ruby python swift typescript sql
      overrides:
          - goos: linux
            goarch: arm64
            env:
                - CGO_ENABLED=1
                - CC=aarch64-linux-gnu-gcc
                - CXX=aarch64-linux-gnu-g++
          - goos: windows
            goarch: amd64
            env:
                - CGO_ENABLED=1
                - CC=x86_64-w64-mingw32-gcc
                - CXX=x86_64-w64-mingw32-g++
      ignore:
          - goos: windows
            goarch: arm64
