name: Release

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'

            - name: Install cross-compilation tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    gcc g++ make \
                    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
                    gcc-mingw-w64 g++-mingw-w64 \
                    mingw-w64
                  echo "Installing tools completed"

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  distribution: goreleaser
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CGO_ENABLED: 1
